services:
  postgres:
    image: pgvector/pgvector:pg17
    restart: unless-stopped
    environment:
      POSTGRES_USER: minha_regiao
      POSTGRES_PASSWORD: minha_regiao
      POSTGRES_DB: minha_regiao
    ports:
      - "9001:5432"
    volumes:
      - minha_regiao_db:/var/lib/postgresql/data

volumes:
  minha_regiao_db:
