    [build-system]

    requires = ["setuptools", "setuptools_scm"]
    build-backend = "setuptools.build_meta"

    ["project"]
    name = "minha_regiao"
    dynamic = ["version"] 
    description = "Python Package that supports the Minha Região Platform"
    readme = "README.md"

    authors = [
        {name = "Rúben Almeida", email = "ruben.f.almeida@inesctec.pt"}
    ]
    requires-python = ">=3.13"

    dependencies = [
        "prefect>=3.6.21",
        "requests",
        "pandas",
        "beautifulsoup4",
        "pydantic",
        "environs",
        "python-dotenv",
        "pydantic-settings",
        "pgvector>=0.4.2",
        "sqlmodel",
        "psycopg[binary,pool]",
    ]

    [project.optional-dependencies]

    instructor = [
        "instructor[openai, google-genai]>=1.14.5"
    ]

    langchain = [
        "langchain>=1.2.11"
    ]

    ollama = [
        "ollama>=0.6.1"
    ]

    hugginface = [
        "huggingface_hub",
    ]

    dev = [
        "minha_regiao[ollama, hugginface, langchain, instructor]"
    ]

    [tool.setuptools.packages.find]
    where = ["src"]
    include = ["propostas_civil", "propostas_civil.*"]
    namespaces = false

    [tool.setuptools_scm]
